/* eslint-disable sort-keys */
export default {
  'BLACK': 'Темная тема',
  'Button': 'Редактировать профиль',
  'Client': 'Клиентский профиль',
  'MyProfile': 'Личный профиль',
  'Title': 'Delta World @ 1970-2077',
  'WHITE': 'Cветлая тема',
  'WritePost': 'Написать пост',
  'authButton': 'Войти',
  'authChange': 'Уже есть аккаунт войти',
  'authorization': 'Авторизоваться',
  'birthday': 'Дата рождения',
  'birthdayError': 'birthdayError',
  'createPost': 'Написать пост',
  'email': 'E-mail',
  'errorEmail': 'Ошибка адресса электронной почты',
  'errorGender': 'Ошибка не выбран пол',
  'errorName': 'Проверьте введенное имя',
  'errorPhone': 'Ошибка номера телефона',
  'errorPhoneIndex': 'Не указан индекс страны начните ввод с +7',
  'exit': 'Выход',
  'female': 'Женский',
  'formErrors': 'formErrors',
  'gender': 'Гендерное предпочтение',
  'genderError': 'genderError',
  'header': 'Delta World',
  'id': 'Личный индефикационный номер пользователя',
  'male': 'Мужской',
  'postEdit': 'Введите текст для поста',
  'mobile': 'Номер телефона',
  'name': 'Имя пользователя',
  'nameError': 'nameError',
  'phone': 'Номер мобильного телефона',
  'phoneError': 'phoneError',
  'placeholderBirthday': '14.07.1990',
  'placeholderEmail': 'example@email.com',
  'placeholderId': '_________-__________-_________-________',
  'placeholderName': 'Якимов Вячеслав Александрович',
  'placeholderPhone': '+79961049357',
  'post': 'Посты',
  'register': 'Регистрация',
  'registerButton': 'Зарегистрировать',
  'registerChange': 'Зарегистрировать аккаунт',
  'signIn': 'Вход',
  'signUn': 'Регистрация',
  'user': 'Пользователи',
};
