/* eslint-disable sort-keys */
export default {
  'BLACK': 'Темная тема',
  'Button': 'Редактировать профиль',
  'Client': 'Клиентский профиль',
  'MyProfile': 'Личный профиль',
  'Title': 'Delta World @ 1970-2077',
  'WHITE': 'Cветлая тема',
  'birthday': 'Дата рождения',
  'createPost': 'Написать пост',
  'email': 'E-mail',
  'exit': 'Выход',
  'gender': 'Пол',
  'header': 'Delta World',
  'id': 'id',
  'mobile': 'Номер Телефона',
  'placeholderId': 'placeholderId',
  'post': 'Посты',
  'register': 'Авторизоваться',
  'registerButton': 'Войти',
  'registerChange': 'Зарегистрировать аккаунт',
  'signIn': 'Вход',
  'signUn': 'Регистрация',
  'user': 'Пользователи',
};
